#include "telemetry.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static const char *TEST_FILE = "telemetry-test.bin"; static const char *CSV_FILE = "telemetry-test.csv"; static const char *RECOVERED_FILE = "telemetry-recovered.bin";
#define CHECK(condition) do { if (!(condition)) { fprintf(stderr, "CHECK failed: %s (%s:%d)\n", #condition, __FILE__, __LINE__); exit(EXIT_FAILURE); } } while (0)
static void reset_files(void) { remove(TEST_FILE); remove(CSV_FILE); remove(RECOVERED_FILE); }
static void seed_three_records(void) { CHECK(telemetry_create_file(TEST_FILE) == TELEMETRY_OK); const telemetry_record records[3] = {{1000, 1, 100, 0}, {2000, 2, 200, 1}, {3000, 1, 300, 2}}; for (size_t i = 0; i < 3; ++i) CHECK(telemetry_append_record(TEST_FILE, &records[i]) == TELEMETRY_OK); }
static void test_round_trip(void) { reset_files(); seed_three_records(); telemetry_record records[3]; size_t count = 0; CHECK(telemetry_read_records(TEST_FILE, records, 3, &count) == TELEMETRY_OK); CHECK(count == 3 && records[1].sensor_id == 2 && records[2].value_milli == 300); reset_files(); }
static void test_invalid_header(void) { FILE *file = fopen(TEST_FILE, "wb"); CHECK(file != NULL); CHECK(fwrite("NOPE", 1, 4, file) == 4); CHECK(fclose(file) == 0); size_t count = 99; CHECK(telemetry_count_records(TEST_FILE, &count) == TELEMETRY_INVALID_FORMAT); CHECK(count == 0); reset_files(); }
static void test_unsupported_version(void) { const unsigned char header[4] = {'G', 'T', 'L', 2}; FILE *file = fopen(TEST_FILE, "wb"); CHECK(file != NULL); CHECK(fwrite(header, 1, sizeof header, file) == sizeof header); CHECK(fclose(file) == 0); size_t count = 99; CHECK(telemetry_count_records(TEST_FILE, &count) == TELEMETRY_UNSUPPORTED_VERSION); CHECK(count == 0); reset_files(); }
static void test_truncated_record_and_append_refusal(void) { reset_files(); CHECK(telemetry_create_file(TEST_FILE) == TELEMETRY_OK); FILE *file = fopen(TEST_FILE, "ab"); CHECK(file != NULL); CHECK(fwrite("abc", 1, 3, file) == 3); CHECK(fclose(file) == 0); size_t count = 0; CHECK(telemetry_count_records(TEST_FILE, &count) == TELEMETRY_TRUNCATED_RECORD); telemetry_record record = {1000, 1, 100, 0}; CHECK(telemetry_append_record(TEST_FILE, &record) == TELEMETRY_TRUNCATED_RECORD); reset_files(); }
static void test_capacity_is_explicit(void) { reset_files(); CHECK(telemetry_create_file(TEST_FILE) == TELEMETRY_OK); telemetry_record record = {1000, 1, 100, 0}; CHECK(telemetry_append_record(TEST_FILE, &record) == TELEMETRY_OK); size_t count = 0; CHECK(telemetry_read_records(TEST_FILE, NULL, 0, &count) == TELEMETRY_CAPACITY_EXCEEDED); CHECK(count == 0); reset_files(); }
static void test_count_and_summary(void) { reset_files(); seed_three_records(); size_t count = 0; CHECK(telemetry_count_records(TEST_FILE, &count) == TELEMETRY_OK); CHECK(count == 3); telemetry_summary summary; CHECK(telemetry_analyze_file(TEST_FILE, &summary) == TELEMETRY_OK); CHECK(summary.record_count == 3); CHECK(summary.first_timestamp_ms == 1000 && summary.last_timestamp_ms == 3000); CHECK(summary.min_value_milli == 100 && summary.max_value_milli == 300 && summary.average_value_milli == 200.0); reset_files(); }
static void test_empty_summary(void) { reset_files(); CHECK(telemetry_create_file(TEST_FILE) == TELEMETRY_OK); telemetry_summary summary; CHECK(telemetry_analyze_file(TEST_FILE, &summary) == TELEMETRY_OK); CHECK(summary.record_count == 0 && summary.average_value_milli == 0.0); reset_files(); }
static void test_invalid_record_is_rejected(void) { reset_files(); CHECK(telemetry_create_file(TEST_FILE) == TELEMETRY_OK); telemetry_record record = {-1, 0, 100, 0}; CHECK(telemetry_append_record(TEST_FILE, &record) == TELEMETRY_INVALID_ARGUMENT); reset_files(); }
typedef struct collect_context { telemetry_record records[3]; size_t count; } collect_context;
static telemetry_result collect_record(const telemetry_record *record, void *context) { collect_context *collect = context; CHECK(collect->count < 3); collect->records[collect->count++] = *record; return TELEMETRY_OK; }
static void test_query_by_sensor_and_half_open_time(void) { reset_files(); seed_three_records(); collect_context collect = {0}; size_t count = 0; telemetry_filter sensor = {.has_sensor = true, .sensor_id = 1}; CHECK(telemetry_query_file(TEST_FILE, &sensor, collect_record, &collect, &count) == TELEMETRY_OK); CHECK(count == 2 && collect.records[0].timestamp_ms == 1000 && collect.records[1].timestamp_ms == 3000); collect = (collect_context){0}; telemetry_filter range = {.has_start_timestamp = true, .start_timestamp_ms = 1000, .has_end_timestamp = true, .end_timestamp_ms = 3000}; CHECK(telemetry_query_file(TEST_FILE, &range, collect_record, &collect, &count) == TELEMETRY_OK); CHECK(count == 2 && collect.records[0].timestamp_ms == 1000 && collect.records[1].timestamp_ms == 2000); reset_files(); }
static void test_invalid_filter_is_rejected(void) { reset_files(); seed_three_records(); collect_context collect = {0}; size_t count = 99; telemetry_filter filter = {.has_start_timestamp = true, .start_timestamp_ms = 3000, .has_end_timestamp = true, .end_timestamp_ms = 3000}; CHECK(telemetry_query_file(TEST_FILE, &filter, collect_record, &collect, &count) == TELEMETRY_INVALID_ARGUMENT); reset_files(); }
static void test_deterministic_csv_export(void) { reset_files(); seed_three_records(); size_t count = 0; telemetry_filter filter = {.has_sensor = true, .sensor_id = 1}; CHECK(telemetry_export_csv(TEST_FILE, CSV_FILE, &filter, &count) == TELEMETRY_OK); CHECK(count == 2); FILE *file = fopen(CSV_FILE, "rb"); CHECK(file != NULL); char content[256] = {0}; const size_t read = fread(content, 1, sizeof content - 1, file); CHECK(!ferror(file)); CHECK(fclose(file) == 0); content[read] = '\0'; CHECK(strcmp(content, "timestamp_ms,sensor_id,value_milli,status\n1000,1,100,0\n3000,1,300,2\n") == 0); reset_files(); }
static void test_diagnostics_exposes_health_without_modifying_source(void) { reset_files(); seed_three_records(); telemetry_diagnostics diagnostics; CHECK(telemetry_diagnose_file(TEST_FILE, &diagnostics) == TELEMETRY_OK); CHECK(diagnostics.stream_result == TELEMETRY_OK); CHECK(diagnostics.record_count == 3 && diagnostics.valid_prefix_bytes == 55); CHECK(diagnostics.first_timestamp_ms == 1000 && diagnostics.last_timestamp_ms == 3000); reset_files(); }
static void test_recovery_copies_only_valid_prefix(void) { reset_files(); seed_three_records(); FILE *file = fopen(TEST_FILE, "ab"); CHECK(file != NULL); CHECK(fwrite("bad", 1, 3, file) == 3); CHECK(fclose(file) == 0); telemetry_diagnostics diagnostics; CHECK(telemetry_diagnose_file(TEST_FILE, &diagnostics) == TELEMETRY_OK); CHECK(diagnostics.stream_result == TELEMETRY_TRUNCATED_RECORD && diagnostics.record_count == 3 && diagnostics.valid_prefix_bytes == 55); size_t recovered = 0; CHECK(telemetry_recover_valid_prefix(TEST_FILE, RECOVERED_FILE, &recovered) == TELEMETRY_OK); CHECK(recovered == 3); size_t count = 0; CHECK(telemetry_count_records(RECOVERED_FILE, &count) == TELEMETRY_OK && count == 3); CHECK(telemetry_count_records(TEST_FILE, &count) == TELEMETRY_TRUNCATED_RECORD); reset_files(); }
static void test_recovery_refuses_invalid_header_without_destination(void) { reset_files(); FILE *file = fopen(TEST_FILE, "wb"); CHECK(file != NULL); CHECK(fwrite("NOPE", 1, 4, file) == 4); CHECK(fclose(file) == 0); size_t recovered = 9; CHECK(telemetry_recover_valid_prefix(TEST_FILE, RECOVERED_FILE, &recovered) == TELEMETRY_INVALID_FORMAT); CHECK(recovered == 0); file = fopen(RECOVERED_FILE, "rb"); CHECK(file == NULL); reset_files(); }
int main(void) { test_round_trip(); test_invalid_header(); test_unsupported_version(); test_truncated_record_and_append_refusal(); test_capacity_is_explicit(); test_count_and_summary(); test_empty_summary(); test_invalid_record_is_rejected(); test_query_by_sensor_and_half_open_time(); test_invalid_filter_is_rejected(); test_deterministic_csv_export(); test_diagnostics_exposes_health_without_modifying_source(); test_recovery_copies_only_valid_prefix(); test_recovery_refuses_invalid_header_without_destination(); puts("telemetry_tests: ok"); return 0; }
