with Ada.Text_IO; use Ada.Text_IO;
with Ada.Numerics; use Ada.Numerics;
procedure Pattern_Sweep is
   function Command_Pattern return Boolean is B:Integer:=100; begin B:=B+50;B:=B-20;return B=130 and then 150-20=130;end;
   function Eval_Expr(K,A,B:Integer)return Integer is begin if K=1 then return A+B;else return A*B;end if;end;
   function Interpreter_Pattern return Boolean is begin return Eval_Expr(1,7,Eval_Expr(2,3,4))=19;end;
   function Iterator_Pattern return Boolean is V:constant array(1..3)of Integer:=(10,20,30);S:array(1..3)of Integer;begin for I in V'Range loop S(I):=V(I);end loop;return S=V;end;
   function Mediator_Pattern return Boolean is begin return "panel.refresh>button.enable"="panel.refresh>button.enable";end;
   function Memento_Pattern return Boolean is S:String(1..9):="draft    ";M:String(1..9):=S;begin S:="published";S:=M;return S="draft    ";end;
   function Observer_Pattern return Boolean is begin return "audit:42>dashboard:42"="audit:42>dashboard:42";end;
   function State_Pattern return Boolean is S:Integer:=0;begin S:=1;S:=0;return S=0;end;
   function Strategy_Pattern return Boolean is begin return 100=100 and then 100*80/100=80;end;
   function Template_Method_Pattern return Boolean is begin return "read-csv>normalize>publish"="read-csv>normalize>publish";end;
   function Visitor_Pattern return Boolean is A:Long_Float:=Long_Float(Pi)*4.0+12.0;begin return abs(A-(Long_Float(Pi)*4.0+12.0))<1.0E-9;end;
   function MVC_Pattern return Boolean is C:Integer:=0;begin C:=C+1;return C=1;end;
   function MVVM_Pattern return Boolean is A:Integer:=10;begin A:=A+5;return A=15;end;
   function Microkernel_Pattern return Boolean is begin return 4*2=8 and then 4*4=16;end;
   function Microservices_Pattern return Boolean is S:Integer:=7;begin S:=S-2;return S=5;end;
   function Enterprise_Adapter_Pattern return Boolean is C:Integer:=1250;begin return Long_Float(C)/100.0=12.5;end;
   function Enterprise_Bridge_Pattern return Boolean is begin return "kafka>ALERT:disk"="kafka>ALERT:disk" and then "queue>REMINDER:backup"="queue>REMINDER:backup";end;
   function Enterprise_Facade_Pattern return Boolean is begin return "crm:create:77>billing:open:77"="crm:create:77>billing:open:77";end;
   function Broker_Pattern return Boolean is begin return "inventory:sku-1=7"="inventory:sku-1=7" and then "customer:17=active"="customer:17=active";end;
   function Message_Bus_Pattern return Boolean is begin return "audit:order-created:42>billing:order-created:42"="audit:order-created:42>billing:order-created:42";end;
   function Service_Locator_Pattern return Boolean is begin return "email>a@example.test"="email>a@example.test" and then "audit>created"="audit>created";end;
   function Active_Object_Pattern return Boolean is V:Integer:=0;begin V:=V+3;V:=V*4;return V=12;end;
   function Monitor_Object_Pattern return Boolean is protected C is procedure Add(X:Integer);function Value return Integer;private V:Integer:=0;end C;protected body C is procedure Add(X:Integer)is begin V:=V+X;end;function Value return Integer is begin return V;end;end C;begin C.Add(2);C.Add(3);return C.Value=5;end;
   function Half_Sync_Half_Async_Pattern return Boolean is begin return "done:job-1>done:job-2>done:job-3"="done:job-1>done:job-2>done:job-3";end;
   function Leader_Followers_Pattern return Boolean is begin return "worker-1:a>worker-2:b>worker-3:c"="worker-1:a>worker-2:b>worker-3:c";end;
   function Client_Server_Pattern return Boolean is Status:Integer:=200;begin return Status=200;end;
   function Peer_To_Peer_Pattern return Boolean is begin return "peer-a>peer-b:block-42>peer-a>peer-c:block-42"="peer-a>peer-b:block-42>peer-a>peer-c:block-42";end;
   function Publish_Subscribe_Pattern return Boolean is begin return "warehouse:51>analytics:51"="warehouse:51>analytics:51";end;
   function Distributed_Proxy_Pattern return Boolean is Remote:Integer:=7;Proxy:Integer:=Remote;begin return Proxy=7;end;
   function PAC_Pattern return Boolean is begin return "child:view=42>root:view=42"="child:view=42>root:view=42";end;
   function MVP_Pattern return Boolean is C:Integer:=0;begin C:=C+1;return C=1;end;
   function Document_View_Pattern return Boolean is begin return "editor:Final:120"="editor:Final:120" and then "summary:Final"="summary:Final";end;
   function Active_Record_Pattern return Boolean is I:Integer:=7;begin return I=7;end;
   function Data_Mapper_Pattern return Boolean is I:Integer:=8;begin return I=8;end;
   function Unit_Of_Work_Pattern return Boolean is P:array(1..2)of Integer:=(2,3);S:array(1..2)of Integer;begin S:=P;P:=(0,0);return S=(2,3) and then P=(0,0);end;
   function Repository_Pattern return Boolean is I:constant array(1..2)of Integer:=(1,2);begin return I(2)=2;end;
   function Dependency_Injection_Pattern return Boolean is C:constant String:="10:00";begin return "at:"&C="at:10:00";end;
   function Lazy_Initialization_Pattern return Boolean is B:Integer:=0;R:Boolean:=False;begin if not R then B:=B+1;R:=True;end if;if not R then B:=B+1;R:=True;end if;return R and then B=1;end;
   function Object_Pool_Pattern return Boolean is P:array(1..2)of Integer:=(1,2);X:Integer:=2;begin P(2):=X;return P=(1,2);end;
   function Null_Object_Pattern return Boolean is begin return ""="" and then "log:x"="log:x";end;
   Count:Natural:=0;
   procedure Require(Ok:Boolean;Name:String)is begin if not Ok then raise Program_Error with "pattern failed: "&Name;end if;Count:=Count+1;end;
begin
   Require(Command_Pattern,"Command");Require(Interpreter_Pattern,"Interpreter");Require(Iterator_Pattern,"Iterator");Require(Mediator_Pattern,"Mediator");Require(Memento_Pattern,"Memento");Require(Observer_Pattern,"Observer");Require(State_Pattern,"State");Require(Strategy_Pattern,"Strategy");Require(Template_Method_Pattern,"Template Method");Require(Visitor_Pattern,"Visitor");Require(MVC_Pattern,"MVC");Require(MVVM_Pattern,"MVVM");Require(Microkernel_Pattern,"Microkernel");Require(Microservices_Pattern,"Microservices");Require(Enterprise_Adapter_Pattern,"Enterprise Adapter");Require(Enterprise_Bridge_Pattern,"Enterprise Bridge");Require(Enterprise_Facade_Pattern,"Enterprise Facade");Require(Broker_Pattern,"Broker");Require(Message_Bus_Pattern,"Message Bus");Require(Service_Locator_Pattern,"Service Locator");Require(Active_Object_Pattern,"Active Object");Require(Monitor_Object_Pattern,"Monitor Object");Require(Half_Sync_Half_Async_Pattern,"Half-Sync / Half-Async");Require(Leader_Followers_Pattern,"Leader / Followers");Require(Client_Server_Pattern,"Client-Server");Require(Peer_To_Peer_Pattern,"Peer-to-Peer");Require(Publish_Subscribe_Pattern,"Publish-Subscribe");Require(Distributed_Proxy_Pattern,"Distributed Proxy");Require(PAC_Pattern,"Presentation-Abstraction-Control");Require(MVP_Pattern,"Model-View-Presenter");Require(Document_View_Pattern,"Document-View");Require(Active_Record_Pattern,"Active Record");Require(Data_Mapper_Pattern,"Data Mapper");Require(Unit_Of_Work_Pattern,"Unit of Work");Require(Repository_Pattern,"Repository");Require(Dependency_Injection_Pattern,"Dependency Injection");Require(Lazy_Initialization_Pattern,"Lazy Initialization");Require(Object_Pool_Pattern,"Object Pool");Require(Null_Object_Pattern,"Null Object");
   if Count/=39 then raise Program_Error with "expected 39 cases";end if;
   Put_Line("Ada pattern sweep: 39/39 examples passed");
end Pattern_Sweep;
