<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" Version="3.10.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../clients/desktop-reference/Genkidama.DesktopReference/Genkidama.DesktopReference.csproj" />
  </ItemGroup>
</Project>
