(ns pattern-sweep)
(defn ok [x] (boolean x))
(defn command-pattern [] (let [cs [(partial + 50) #(- % 20)] b (reduce #(%2 %1) 100 cs)] (and (= b 130) (= ((second cs) 150) 130))))
(defn interpreter-pattern [] (letfn [(ev [e] (case (first e) :lit (second e) :add (+ (ev (second e)) (ev (nth e 2))) :mul (* (ev (second e)) (ev (nth e 2)))))] (= 19 (ev [:add [:lit 7] [:mul [:lit 3] [:lit 4]]]))))
(defn iterator-pattern [] (= [10 20 30] (vec (iterator-seq (.iterator [10 20 30])))))
(defn mediator-pattern [] (let [events (atom []) notify #(cond (and (= %1 :button)(= %2 :click))(swap! events conj :panel.refresh) (and (= %1 :panel)(= %2 :loaded))(swap! events conj :button.enable) :else nil)] (notify :button :click)(notify :panel :loaded)(= @events [:panel.refresh :button.enable])))
(defn memento-pattern [] (let [state (atom "draft") snap @state] (reset! state "published")(reset! state snap)(= @state "draft")))
(defn observer-pattern [] (= ["audit:42" "dashboard:42"] (mapv #(% 42) [(fn [i](str "audit:" i))(fn [i](str "dashboard:" i))])))
(defn state-pattern [] (let [t #(cond (and (= %1 :locked)(= %2 :unlock)) :unlocked (and (= %1 :unlocked)(= %2 :lock)) :locked :else %1)] (= :locked (t (t :locked :unlock) :lock))))
(defn strategy-pattern [] (let [price #(%2 %1)] (and (= 100 (price 100 identity)) (= 80 (price 100 #(* % 8/10))))))
(defn template-method-pattern [] (= "read-csv>normalize>publish" ((fn [r t](str r ">" (t) ">publish")) "read-csv" (constantly "normalize"))))
(defn visitor-pattern [] (let [area #(case (:kind %) :circle (* Math/PI (:r %) (:r %)) :rect (* (:w %) (:h %)))] (< (Math/abs (- (reduce + (map area [{:kind :circle :r 2.0}{:kind :rect :w 3.0 :h 4.0}])) (+ (* 4 Math/PI) 12))) 1e-9)))
(defn mvc-pattern [] (let [m (atom 0) view #(str "count=" @m) before (view)] (swap! m inc)(and (= before "count=0")(= (view) "count=1"))))
(defn mvvm-pattern [] (let [v (atom 10) text #(str "$" @v ".00") before (text)] (swap! v + 5)(and (= before "$10.00")(= (text) "$15.00"))))
(defn microkernel-pattern [] (let [p {:double #(* 2 %) :square #(* % %)}] (and (= 8 ((:double p) 4))(= 16 ((:square p) 4)))))
(defn microservices-pattern [] (let [stock (atom 7) reserve #(if (> % @stock) false (do (swap! stock - %) true))] (and (= "confirmed" (if (reserve 2) "confirmed" "rejected"))(= @stock 5))))
(defn enterprise-adapter-pattern [] (= {:id 17 :amount 12.5} (let [l {:code 17 :cents 1250}] {:id (:code l):amount (/ (:cents l) 100.0)})))
(defn enterprise-bridge-pattern [] (let [send #(str %1 ">" %2 ":" %3)] (and (= "kafka>ALERT:disk" (send "kafka" "ALERT" "disk"))(= "queue>REMINDER:backup" (send "queue" "REMINDER" "backup")))))
(defn enterprise-facade-pattern [] (= "crm:create:77>billing:open:77" (str "crm:create:77" ">" "billing:open:77")))
(defn broker-pattern [] (let [s {:inventory #(str "inventory:" % "=7") :customer #(str "customer:" % "=active")}] (and (= "inventory:sku-1=7" ((:inventory s) "sku-1"))(= "customer:17=active" ((:customer s) "17")))))
(defn message-bus-pattern [] (= ["audit:order-created:42" "billing:order-created:42"] (mapv #(% "order-created" 42) [(fn[t i](str "audit:" t ":" i))(fn[t i](str "billing:" t ":" i))])))
(defn service-locator-pattern [] (let [s {:email #(str "email>" %) :audit #(str "audit>" %)}] (and (= "email>a@example.test" ((:email s) "a@example.test"))(= "audit>created" ((:audit s) "created")))))
(defn active-object-pattern [] (let [v (atom 0) q [#(swap! v + 3) #(swap! v * 4)] before @v] (doseq [c q](c))(and (= before 0)(= @v 12))))
(defn monitor-object-pattern [] (let [v (atom 0) lock (Object.) add #(locking lock (swap! v + %))] (add 2)(add 3)(= @v 5)))
(defn half-sync-half-async-pattern [] (= ["done:job-1" "done:job-2" "done:job-3"] (mapv #(str "done:" %) ["job-1" "job-2" "job-3"])))
(defn leader-followers-pattern [] (= ["worker-1:a" "worker-2:b" "worker-3:c"] (mapv #(str %1 ":" %2) ["worker-1" "worker-2" "worker-3"] ["a" "b" "c"])))
(defn client-server-pattern [] (= {:status 200 :body "stock=7"} ((fn[k](if (= k "sku-1"){:status 200 :body "stock=7"}{:status 404 :body "missing"})) "sku-1")))
(defn peer-to-peer-pattern [] (= ["peer-a>peer-b:block-42" "peer-a>peer-c:block-42"] (mapv #(str "peer-a>" % ":block-42") ["peer-b" "peer-c"])))
(defn publish-subscribe-pattern [] (= ["warehouse:51" "analytics:51"] (mapv #(% 51) [(fn[i](str "warehouse:" i))(fn[i](str "analytics:" i))])))
(defn distributed-proxy-pattern [] (= 7 (((fn [remote] (fn [sku] (remote sku))) (fn [sku] (if (= sku "sku-1") 7 0))) "sku-1")))
(defn pac-pattern [] (= ["child:view=42" "root:view=42"] (mapv #(str % ":view=42") ["child" "root"])))
(defn mvp-pattern [] (let [m (atom 0) v (atom "")] (swap! m inc)(reset! v (str "count=" @m))(and (= @m 1)(= @v "count=1"))))
(defn document-view-pattern [] (= ["editor:Final:120" "summary:Final"] [(str "editor:Final:" 120) "summary:Final"]))
(defn active-record-pattern [] (let [t (atom {})] (swap! t assoc 7 "Ada")(= "Ada" (@t 7))))
(defn data-mapper-pattern [] (= {:key "person:8" :name "Grace"} (let[p {:id 8 :name "Grace"}]{:key (str "person:" (:id p)):name (:name p)})))
(defn unit-of-work-pattern [] (let [store(atom[])pending(atom[2 3])] (swap! store into @pending)(reset! pending [])(and (= @store [2 3])(empty? @pending))))
(defn repository-pattern [] (= "Grace" (:name (first (filter #(= 2 (:id %)) [{:id 1 :name "Ada"} {:id 2 :name "Grace"}])))))
(defn dependency-injection-pattern [] (= "at:10:00" ((fn[clock](str "at:" (clock))) (constantly "10:00"))))
(defn lazy-initialization-pattern [] (let [builds(atom 0) v(delay(do(swap! builds inc)"ready"))] (and (= @v "ready")(= @v "ready")(= @builds 1))))
(defn object-pool-pattern [] (let [pool(atom[1 2]) x(last @pool)] (swap! pool pop)(swap! pool conj x)(and (= 2(count @pool))(some #{x}@pool))))
(defn null-object-pattern [] (let [null-log(constantly "") real-log #(str "log:" %)] (and (= ""(null-log "x"))(= "log:x"(real-log "x")))))
(def cases [command-pattern interpreter-pattern iterator-pattern mediator-pattern memento-pattern observer-pattern state-pattern strategy-pattern template-method-pattern visitor-pattern mvc-pattern mvvm-pattern microkernel-pattern microservices-pattern enterprise-adapter-pattern enterprise-bridge-pattern enterprise-facade-pattern broker-pattern message-bus-pattern service-locator-pattern active-object-pattern monitor-object-pattern half-sync-half-async-pattern leader-followers-pattern client-server-pattern peer-to-peer-pattern publish-subscribe-pattern distributed-proxy-pattern pac-pattern mvp-pattern document-view-pattern active-record-pattern data-mapper-pattern unit-of-work-pattern repository-pattern dependency-injection-pattern lazy-initialization-pattern object-pool-pattern null-object-pattern])
(doseq [f cases] (assert (f)))
(assert (= 39 (count cases)))
(println "Clojure pattern sweep: 39/39 examples passed")
